{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2023-40590",
				"title": "Title"
			},
			{
				"category": "description",
				"text": " GitPython is a python library used to interact with Git repositories. When resolving a program, Python/Windows look for the current working directory, and after that the PATH environment. GitPython defaults to use the `git` command, if a user runs GitPython from a repo has a `git.exe` or `git` executable, that program will be run instead of the one in the user's `PATH`. This is more of a problem on how Python interacts with Windows systems, Linux and any other OS aren't affected by this. But probably people using GitPython usually run it from the CWD of a repo. An attacker can trick a user to download a repository with a malicious `git` executable, if the user runs/imports GitPython from that directory, it allows the attacker to run any arbitrary commands. There is no fix currently available for windows users, however there are a few mitigations. 1: Default to an absolute path for the git program on Windows, like `C:\\\\Program Files\\\\Git\\\\cmd\\\\git.EXE` (default git path installation). 2: Require users to set the `GIT_PYTHON_GIT_EXECUTABLE` environment variable on Windows systems. 3: Make this problem prominent in the documentation and advise users to never run GitPython from an untrusted repo, or set the `GIT_PYTHON_GIT_EXECUTABLE` env var to an absolute path. 4: Resolve the executable manually by only looking into the `PATH` environment variable.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2023-40590",
				"url": "https://www.suse.com/security/cve/CVE-2023-40590"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1214734 for CVE-2023-40590",
				"url": "https://bugzilla.suse.com/1214734"
			}
		],
		"title": "SUSE CVE CVE-2023-40590",
		"tracking": {
			"current_release_date": "2023-09-08T02:14:43Z",
			"generator": {
				"date": "2023-08-30T02:14:30Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2023-40590",
			"initial_release_date": "2023-08-30T02:14:30Z",
			"revision_history": [
				{
					"date": "2023-08-30T02:14:30Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2023-09-08T02:14:43Z",
					"number": "3",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "HPE Helion OpenStack 8",
								"product": {
									"name": "HPE Helion OpenStack 8",
									"product_id": "HPE Helion OpenStack 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:hpe-helion-openstack:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 8",
								"product": {
									"name": "SUSE OpenStack Cloud 8",
									"product_id": "SUSE OpenStack Cloud 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 9",
								"product": {
									"name": "SUSE OpenStack Cloud 9",
									"product_id": "SUSE OpenStack Cloud 9",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:9"
									}
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-GitPython",
								"product": {
									"name": "python-GitPython",
									"product_id": "python-GitPython"
								}
							},
							{
								"category": "product_version",
								"name": "python310-GitPython-3.1.34.1693646983.2a2ae77-1.1",
								"product": {
									"name": "python310-GitPython-3.1.34.1693646983.2a2ae77-1.1",
									"product_id": "python310-GitPython-3.1.34.1693646983.2a2ae77-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python311-GitPython-3.1.34.1693646983.2a2ae77-1.1",
								"product": {
									"name": "python311-GitPython-3.1.34.1693646983.2a2ae77-1.1",
									"product_id": "python311-GitPython-3.1.34.1693646983.2a2ae77-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python39-GitPython-3.1.34.1693646983.2a2ae77-1.1",
								"product": {
									"name": "python39-GitPython-3.1.34.1693646983.2a2ae77-1.1",
									"product_id": "python39-GitPython-3.1.34.1693646983.2a2ae77-1.1"
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-GitPython-3.1.34.1693646983.2a2ae77-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-GitPython-3.1.34.1693646983.2a2ae77-1.1"
				},
				"product_reference": "python310-GitPython-3.1.34.1693646983.2a2ae77-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-GitPython-3.1.34.1693646983.2a2ae77-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-GitPython-3.1.34.1693646983.2a2ae77-1.1"
				},
				"product_reference": "python311-GitPython-3.1.34.1693646983.2a2ae77-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-GitPython-3.1.34.1693646983.2a2ae77-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-GitPython-3.1.34.1693646983.2a2ae77-1.1"
				},
				"product_reference": "python39-GitPython-3.1.34.1693646983.2a2ae77-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-GitPython as component of HPE Helion OpenStack 8",
					"product_id": "HPE Helion OpenStack 8:python-GitPython"
				},
				"product_reference": "python-GitPython",
				"relates_to_product_reference": "HPE Helion OpenStack 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-GitPython as component of SUSE OpenStack Cloud 8",
					"product_id": "SUSE OpenStack Cloud 8:python-GitPython"
				},
				"product_reference": "python-GitPython",
				"relates_to_product_reference": "SUSE OpenStack Cloud 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-GitPython as component of SUSE OpenStack Cloud 9",
					"product_id": "SUSE OpenStack Cloud 9:python-GitPython"
				},
				"product_reference": "python-GitPython",
				"relates_to_product_reference": "SUSE OpenStack Cloud 9"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-40590",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-40590"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": " GitPython is a python library used to interact with Git repositories. When resolving a program, Python/Windows look for the current working directory, and after that the PATH environment. GitPython defaults to use the `git` command, if a user runs GitPython from a repo has a `git.exe` or `git` executable, that program will be run instead of the one in the user's `PATH`. This is more of a problem on how Python interacts with Windows systems, Linux and any other OS aren't affected by this. But probably people using GitPython usually run it from the CWD of a repo. An attacker can trick a user to download a repository with a malicious `git` executable, if the user runs/imports GitPython from that directory, it allows the attacker to run any arbitrary commands. There is no fix currently available for windows users, however there are a few mitigations. 1: Default to an absolute path for the git program on Windows, like `C:\\\\Program Files\\\\Git\\\\cmd\\\\git.EXE` (default git path installation). 2: Require users to set the `GIT_PYTHON_GIT_EXECUTABLE` environment variable on Windows systems. 3: Make this problem prominent in the documentation and advise users to never run GitPython from an untrusted repo, or set the `GIT_PYTHON_GIT_EXECUTABLE` env var to an absolute path. 4: Resolve the executable manually by only looking into the `PATH` environment variable.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"openSUSE Tumbleweed:python310-GitPython-3.1.34.1693646983.2a2ae77-1.1",
					"openSUSE Tumbleweed:python311-GitPython-3.1.34.1693646983.2a2ae77-1.1",
					"openSUSE Tumbleweed:python39-GitPython-3.1.34.1693646983.2a2ae77-1.1"
				],
				"known not affected": [
					"HPE Helion OpenStack 8:python-GitPython",
					"SUSE OpenStack Cloud 8:python-GitPython",
					"SUSE OpenStack Cloud 9:python-GitPython"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-40590",
					"url": "https://www.suse.com/security/cve/CVE-2023-40590"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1214734 for CVE-2023-40590",
					"url": "https://bugzilla.suse.com/1214734"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-GitPython-3.1.34.1693646983.2a2ae77-1.1",
						"openSUSE Tumbleweed:python311-GitPython-3.1.34.1693646983.2a2ae77-1.1",
						"openSUSE Tumbleweed:python39-GitPython-3.1.34.1693646983.2a2ae77-1.1"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.8,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python310-GitPython-3.1.34.1693646983.2a2ae77-1.1",
						"openSUSE Tumbleweed:python311-GitPython-3.1.34.1693646983.2a2ae77-1.1",
						"openSUSE Tumbleweed:python39-GitPython-3.1.34.1693646983.2a2ae77-1.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2023-08-28T20:02:13Z",
					"details": "important"
				}
			],
			"title": "CVE-2023-40590"
		}
	]
}
