{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2025 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2016-2512",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2016-2512",
				"url": "https://www.suse.com/security/cve/CVE-2016-2512"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 967999 for CVE-2016-2512",
				"url": "https://bugzilla.suse.com/967999"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2018:1102-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2018:1828-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004225.html"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2018:1830-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004226.html"
			}
		],
		"title": "SUSE CVE CVE-2016-2512",
		"tracking": {
			"current_release_date": "2025-01-01T10:05:37Z",
			"generator": {
				"date": "2023-02-15T05:05:54Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2016-2512",
			"initial_release_date": "2023-02-15T05:05:54Z",
			"revision_history": [
				{
					"date": "2023-02-15T05:05:54Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2023-12-08T04:37:25Z",
					"number": "3",
					"summary": "Current version"
				},
				{
					"date": "2025-01-01T10:05:37Z",
					"number": "4",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "4"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 4",
								"product": {
									"name": "SUSE Enterprise Storage 4",
									"product_id": "SUSE Enterprise Storage 4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:4"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 5",
								"product": {
									"name": "SUSE Enterprise Storage 5",
									"product_id": "SUSE Enterprise Storage 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:5"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 6",
								"product": {
									"name": "SUSE OpenStack Cloud 6",
									"product_id": "SUSE OpenStack Cloud 6",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:6"
									}
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django-1.6.11-5.5.1",
								"product": {
									"name": "python-Django-1.6.11-5.5.1",
									"product_id": "python-Django-1.6.11-5.5.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.6.11:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django-1.6.11-6.5.1",
								"product": {
									"name": "python-Django-1.6.11-6.5.1",
									"product_id": "python-Django-1.6.11-6.5.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.6.11:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django-1.8.19-3.6.1",
								"product": {
									"name": "python-Django-1.8.19-3.6.1",
									"product_id": "python-Django-1.8.19-3.6.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.8.19:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3-Django-1.10.4-1.1",
								"product": {
									"name": "python3-Django-1.10.4-1.1",
									"product_id": "python3-Django-1.10.4-1.1"
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.6.11-5.5.1 as component of SUSE Enterprise Storage 4",
					"product_id": "SUSE Enterprise Storage 4:python-Django-1.6.11-5.5.1"
				},
				"product_reference": "python-Django-1.6.11-5.5.1",
				"relates_to_product_reference": "SUSE Enterprise Storage 4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.6.11-6.5.1 as component of SUSE Enterprise Storage 5",
					"product_id": "SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1"
				},
				"product_reference": "python-Django-1.6.11-6.5.1",
				"relates_to_product_reference": "SUSE Enterprise Storage 5"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.8.19-3.6.1 as component of SUSE OpenStack Cloud 6",
					"product_id": "SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1"
				},
				"product_reference": "python-Django-1.8.19-3.6.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 6"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-Django-1.10.4-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python3-Django-1.10.4-1.1"
				},
				"product_reference": "python3-Django-1.10.4-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2016-2512",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2016-2512"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Enterprise Storage 4:python-Django-1.6.11-5.5.1",
					"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1",
					"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
					"openSUSE Tumbleweed:python3-Django-1.10.4-1.1"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2016-2512",
					"url": "https://www.suse.com/security/cve/CVE-2016-2512"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 967999 for CVE-2016-2512",
					"url": "https://bugzilla.suse.com/967999"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2018:1102-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2018:1828-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004225.html"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2018:1830-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004226.html"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-Django-1.6.11-5.5.1",
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1",
						"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
						"openSUSE Tumbleweed:python3-Django-1.10.4-1.1"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.4,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:H/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-Django-1.6.11-5.5.1",
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1",
						"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
						"openSUSE Tumbleweed:python3-Django-1.10.4-1.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2016-02-24T10:28:27Z",
					"details": "important"
				}
			],
			"title": "CVE-2016-2512"
		}
	]
}
