{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2021-45115",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2021-45115",
				"url": "https://www.suse.com/security/cve/CVE-2021-45115"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1194115 for CVE-2021-45115",
				"url": "https://bugzilla.suse.com/1194115"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1194117 for CVE-2021-45115",
				"url": "https://bugzilla.suse.com/1194117"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2022:0102-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010010.html"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2022:0103-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010016.html"
			},
			{
				"category": "external",
				"summary": "Advisory link for openSUSE-SU-2023:0005-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/UHF5IZKTZ2T4T4QQYZMUFHW422X3WCU6/"
			}
		],
		"title": "SUSE CVE CVE-2021-45115",
		"tracking": {
			"current_release_date": "2023-02-15T03:36:22Z",
			"generator": {
				"date": "2023-02-15T03:36:22Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2021-45115",
			"initial_release_date": "2023-02-15T03:36:22Z",
			"revision_history": [
				{
					"date": "2023-02-15T03:36:22Z",
					"number": "2",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "2"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "HPE Helion OpenStack 8",
								"product": {
									"name": "HPE Helion OpenStack 8",
									"product_id": "HPE Helion OpenStack 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:hpe-helion-openstack:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 8",
								"product": {
									"name": "SUSE OpenStack Cloud 8",
									"product_id": "SUSE OpenStack Cloud 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 9",
								"product": {
									"name": "SUSE OpenStack Cloud 9",
									"product_id": "SUSE OpenStack Cloud 9",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:9"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud Crowbar 8",
								"product": {
									"name": "SUSE OpenStack Cloud Crowbar 8",
									"product_id": "SUSE OpenStack Cloud Crowbar 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud-crowbar:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud Crowbar 9",
								"product": {
									"name": "SUSE OpenStack Cloud Crowbar 9",
									"product_id": "SUSE OpenStack Cloud Crowbar 9",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud-crowbar:9"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE Package Hub 15 SP3",
								"product": {
									"name": "SUSE Package Hub 15 SP3",
									"product_id": "SUSE Package Hub 15 SP3"
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Leap 15.3",
								"product": {
									"name": "openSUSE Leap 15.3",
									"product_id": "openSUSE Leap 15.3",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:leap:15.3"
									}
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django-1.11.29-3.33.1",
								"product": {
									"name": "python-Django-1.11.29-3.33.1",
									"product_id": "python-Django-1.11.29-3.33.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.11.29:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django1-1.11.29-3.30.1",
								"product": {
									"name": "python-Django1-1.11.29-3.30.1",
									"product_id": "python-Django1-1.11.29-3.30.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.11.29:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3-Django-2.2.28-bp153.2.3.1",
								"product": {
									"name": "python3-Django-2.2.28-bp153.2.3.1",
									"product_id": "python3-Django-2.2.28-bp153.2.3.1"
								}
							},
							{
								"category": "product_version",
								"name": "python310-Django-4.0.1-1.1",
								"product": {
									"name": "python310-Django-4.0.1-1.1",
									"product_id": "python310-Django-4.0.1-1.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:4.0.1:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python38-Django-4.0.1-1.1",
								"product": {
									"name": "python38-Django-4.0.1-1.1",
									"product_id": "python38-Django-4.0.1-1.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:4.0.1:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python39-Django-4.0.1-1.1",
								"product": {
									"name": "python39-Django-4.0.1-1.1",
									"product_id": "python39-Django-4.0.1-1.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:4.0.1:*:*:*:*:*:*:*"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.33.1 as component of HPE Helion OpenStack 8",
					"product_id": "HPE Helion OpenStack 8:python-Django-1.11.29-3.33.1"
				},
				"product_reference": "python-Django-1.11.29-3.33.1",
				"relates_to_product_reference": "HPE Helion OpenStack 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.33.1 as component of SUSE OpenStack Cloud 8",
					"product_id": "SUSE OpenStack Cloud 8:python-Django-1.11.29-3.33.1"
				},
				"product_reference": "python-Django-1.11.29-3.33.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django1-1.11.29-3.30.1 as component of SUSE OpenStack Cloud 9",
					"product_id": "SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.30.1"
				},
				"product_reference": "python-Django1-1.11.29-3.30.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 9"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.33.1 as component of SUSE OpenStack Cloud Crowbar 8",
					"product_id": "SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.33.1"
				},
				"product_reference": "python-Django-1.11.29-3.33.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud Crowbar 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django1-1.11.29-3.30.1 as component of SUSE OpenStack Cloud Crowbar 9",
					"product_id": "SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.30.1"
				},
				"product_reference": "python-Django1-1.11.29-3.30.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud Crowbar 9"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-Django-2.2.28-bp153.2.3.1 as component of SUSE Package Hub 15 SP3",
					"product_id": "SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1"
				},
				"product_reference": "python3-Django-2.2.28-bp153.2.3.1",
				"relates_to_product_reference": "SUSE Package Hub 15 SP3"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-Django-2.2.28-bp153.2.3.1 as component of openSUSE Leap 15.3",
					"product_id": "openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1"
				},
				"product_reference": "python3-Django-2.2.28-bp153.2.3.1",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-Django-4.0.1-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-Django-4.0.1-1.1"
				},
				"product_reference": "python310-Django-4.0.1-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python38-Django-4.0.1-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python38-Django-4.0.1-1.1"
				},
				"product_reference": "python38-Django-4.0.1-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-Django-4.0.1-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-Django-4.0.1-1.1"
				},
				"product_reference": "python39-Django-4.0.1-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2021-45115",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-45115"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-45115",
					"url": "https://www.suse.com/security/cve/CVE-2021-45115"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1194115 for CVE-2021-45115",
					"url": "https://bugzilla.suse.com/1194115"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1194117 for CVE-2021-45115",
					"url": "https://bugzilla.suse.com/1194117"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2022:0102-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010010.html"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2022:0103-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010016.html"
				},
				{
					"category": "external",
					"summary": "Advisory link for openSUSE-SU-2023:0005-1",
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/UHF5IZKTZ2T4T4QQYZMUFHW422X3WCU6/"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"HPE Helion OpenStack 8:python-Django-1.11.29-3.33.1",
						"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.33.1",
						"SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.30.1",
						"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.33.1",
						"SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.30.1",
						"SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Tumbleweed:python310-Django-4.0.1-1.1",
						"openSUSE Tumbleweed:python38-Django-4.0.1-1.1",
						"openSUSE Tumbleweed:python39-Django-4.0.1-1.1"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"HPE Helion OpenStack 8:python-Django-1.11.29-3.33.1",
						"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.33.1",
						"SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.30.1",
						"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.33.1",
						"SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.30.1",
						"SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Tumbleweed:python310-Django-4.0.1-1.1",
						"openSUSE Tumbleweed:python38-Django-4.0.1-1.1",
						"openSUSE Tumbleweed:python39-Django-4.0.1-1.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-12-28T16:04:45Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-45115"
		}
	]
}
